Banner/Areas/Admin/Controllers/AccountSetController.cs
using Banner.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Data.SqlTypes;
using System.Drawing;
using System.Linq;
using System.Security.Cryptography;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Web.Security.AntiXss;
using System.Web.UI.WebControls;
using static Banner.Areas.Admin.Controllers.AccountSetController;
using static Banner.Areas.Admin.Controllers.AccountSetController;

namespace Banner.Areas.Admin.Controllers
{
    public class AccountSetController : PublicClass
    {
        // GET: Admin/AccountSet
        public ActionResult Index()
        {
            return View();
        }

        #region 牧養名單-列表
        public class cAccount_List : PublicClass
        {
            public cTableList cTL = new cTableList();
            public string sAddURL = "/Admin/AccountSet/Account_Aldult_Edit/0";
            public string Name = "";
            public string CellPhone = "";
            public int CellPhoneZipID = 0;
            public int Sex = 0;
            public int OID = 8;
            public string OTitle = "";
            public string TargetDate = "";
            public bool bPoorFlag = false;
            public ListSelect LS_Baptized = new ListSelect();
            public ListSelect LS_Group = new ListSelect();

            public cAccount_List()
            {
                if (LS_Baptized == null)
                    LS_Baptized = new ListSelect();
                LS_Baptized.ControlName = "ddl_Baptized";
                LS_Baptized.Title = "受洗狀態";
                LS_Baptized.ddlList.Add(new SelectListItem { Text = "請選擇", Value = "0", Selected = true });
                LS_Baptized.ddlList.Add(new SelectListItem { Text = "已受洗", Value = "1" });
                LS_Baptized.ddlList.Add(new SelectListItem { Text = "未受洗", Value = "2" });

                if (LS_Group == null)
                    LS_Group = new ListSelect();
                LS_Group.ControlName = "ddl_Group";
                LS_Group.Title = "入組狀態";
                LS_Group.ddlList.Add(new SelectListItem { Text = "請選擇", Value = "0", Selected = true });
                for (int i = 0; i < JoinTitle.Length; i++)
                    LS_Group.ddlList.Add(new SelectListItem { Text = JoinTitle[i], Value = (i + 1).ToString(), Disabled = i == 2 });
            }

        }

        public cAccount_List sAccount_Aldult_List(FormCollection FC)
        {
            cAccount_List cAL = new cAccount_List();
            cAL.cTL = new cTableList();
            if (FC != null)
            {
                cAL.Name = FC.Get("txb_Name");
                cAL.CellPhone = FC.Get("txb_CellPhone");
                cAL.Sex = Convert.ToInt32(FC.Get("rbl_Sex"));
                cAL.CellPhone = FC.Get("txb_PhoneNo");
                cAL.CellPhoneZipID = Convert.ToInt32(FC.Get("ddl_PhoneZip"));
                cAL.TargetDate = FC.Get("txb_TargetDate");
                cAL.bPoorFlag = GetViewCheckBox(FC.Get("cbox_PoorFlag"));
                if (FC.Get("ddl_Baptized") != null)
                {
                    cAL.LS_Baptized.ddlList.ForEach(q => q.Selected = false);
                    cAL.LS_Baptized.ddlList.First(q => q.Value == FC.Get("ddl_Baptized")).Selected = true;
                }

                if (FC.Get("ddl_Group") != null)
                {
                    cAL.LS_Group.ddlList.ForEach(q => q.Selected = false);
                    cAL.LS_Group.ddlList.First(q => q.Value == FC.Get("ddl_Group")).Selected = true;
                }

                if (FC.Get("txb_OTitle") != null)
                {
                    cAL.OTitle = FC.Get("txb_OTitle");
                }

            }

            return cAL;
        }
        public cTableList GetAccountTable(int iType, FormCollection FC)
        {
            cTableList cTL = new cTableList();
            int iNumCut = Convert.ToInt32(FC != null ? FC.Get("ddl_ChangePageCut") : "10");
            int iNowPage = Convert.ToInt32(FC != null ? FC.Get("hid_NextPage") : "1");
            ACID = GetACID();
            cTL.Title = "";
            cTL.NowPage = iNowPage;
            cTL.NumCut = iNumCut;
            cTL.Rs = new List<cTableRow>();

            var Ns = DC.Account.Where(q => !q.DeleteFlag);
            #region 後台全職同工可檢視旌旗資料判斷
            {
                if (ACID != 1)
                {
                    var MOI2 = DC.M_OI2_Account.FirstOrDefault(q => q.OIID == 1 && q.ACID == ACID && !q.DeleteFlag && q.ActiveFlag);
                    if (MOI2 == null)//他沒有全部的權限
                    {
                        MOI2 = DC.M_OI2_Account.FirstOrDefault(q => q.OIID == 2 && q.ACID == ACID && !q.DeleteFlag && q.ActiveFlag);
                        if (MOI2 == null)//他沒有看未入組的會員權限=需要依據他的旌旗角色篩選
                        {
                            MOI2 = DC.M_OI2_Account.FirstOrDefault(q => q.ACID == ACID && !q.DeleteFlag && q.ActiveFlag);
                            if (MOI2 == null)//不具備旌旗的權限
                            {
                                Ns = Ns.Where(q => q.ACID == 0);
                            }
                            else
                            {
                                var OI8_ACIDs = from q in (from q in DC.M_OI2_Account.Where(q => q.ACID == ACID && !q.DeleteFlag && q.ActiveFlag)
                                                           join p in GetMOIAC(8, 0, 0)
                                                           on q.OIID equals p.OrganizeInfo.OI2_ID
                                                           select p)
                                                group q by new { q.ACID } into g
                                                select new { g.Key.ACID };

                                Ns = from q in OI8_ACIDs
                                     join p in Ns
                                     on q.ACID equals p.ACID
                                     select p;
                            }
                        }
                        else
                        {
                            var M_ACIDs = from q in DC.M_OI_Account.Where(q => q.ActiveFlag && !q.DeleteFlag && q.CreDate != q.JoinDate && q.OIID > 0)
                                          group q by new { q.ACID } into g
                                          select new { g.Key.ACID };
                            var ACIDs = from q in Ns
                                        group q by new { q.ACID } into g
                                        select new { g.Key.ACID };
                            Ns = from q in ACIDs.Except(M_ACIDs)
                                 join p in Ns
                                 on q.ACID equals p.ACID
                                 select p;
                        }
                    }
                }

            }
            #endregion

            switch (iType)
            {
                case 1://成人
                    {
                        cTL.NowURL = "/Admin/AccountSet/Account_Aldult_List";
                        Ns = Ns.Where(q => DT.Year - q.Birthday.Year > iChildAge && q.Birthday != q.CreDate);
                    }
                    break;

                case 2://兒童
                    {
                        cTL.NowURL = "/Admin/AccountSet/Account_Childen_List";
                        Ns = Ns.Where(q => DT.Year - q.Birthday.Year <= iChildAge && q.Birthday != q.CreDate);
                    }
                    break;

                case 3://新人
                    {
                        cTL.NowURL = "/Admin/AccountSet/Account_New_List";
                        //先過濾仍在小組內的人
                        var M_OI_AGs = from q in DC.M_OI_Account.Where(q => !q.DeleteFlag)
                                       group q by new { q.ACID } into g
                                       select new { g.Key.ACID, MaxID = g.Max(q => q.MID), Ct = g.Count() };
                        var M_OI_As = from q in DC.M_OI_Account.Where(q => !q.DeleteFlag)
                                      join p in M_OI_AGs
                                      on q.MID equals p.MaxID
                                      select q;
                        var AIDs = (Ns.Select(q => q.ACID)).Except(M_OI_As.Where(q => q.OIID > 1 && q.JoinDate != q.CreDate).Select(q => q.ACID));

                    }
                    break;

                case 4://受洗
                    {
                        cTL.NowURL = "/Admin/AccountSet/Account_Baptized_List";
                        //Ns = Ns.Where(q => DT.Year - q.Birthday.Year > iChildAge && q.BaptizedType == 0);//小朋友不能受洗
                        //Ns = Ns.Where(q => q.BaptizedType == 0);//小朋友可以受洗

                        //小朋友不在受洗名單範圍內,且不考慮未入組名單
                        /*Ns = from q in Ns.Where(q => DT.Year - q.Birthday.Year > iChildAge && q.BaptizedType == 0)
                             join p in GetMOIAC().Where(q => q.OIID > 1).GroupBy(q => q.ACID).Select(q => q.Key)
                             on q.ACID equals p
                             select q;*/
                        //排除未被指定受洗日期的會員
                        Ns = from q in DC.Baptized.Where(q => !q.ImplementFlag && !q.DeleteFlag && q.BaptismDate != q.CreDate).GroupBy(q => q.ACID).Select(q => q.Key)
                             join p in Ns
                             on q equals p.ACID
                             select p;
                    }
                    break;

                case 5://會友
                    {
                        cTL.NowURL = "/Admin/AccountSet/Account_Aldult_List";
                        Ns = from q in Ns.Where(q => DT.Year - q.Birthday.Year > iChildAge && q.Birthday != q.CreDate)
                             join p in DC.M_Role_Account.Where(q => q.ActiveFlag && !q.DeleteFlag && q.RID == 2).GroupBy(q => q.ACID).Select(q => q.Key)

Banner/Controllers/IncludeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Banner.Controllers
{
    public class IncludeController : PublicClass
    {
        //改小組
        public PartialViewResult _ChangeGroup()
        {
            return PartialView();
        }
    }
}

Banner/Areas/Admin/Views/AccountSet/Account_Aldult_List.cshtml
@model Banner.Areas.Admin.Controllers.AccountSetController.cAccount_List
@{
    Layout = "~/Areas/Admin/Views/Include/_Master.cshtml";
}

<div class="main-container">
    <div class="header-container">
        <div class="header-left-border"></div>
        <h5 class="header font-bold">@ViewBag._Title</h5>
    </div>
    <div class="body-container">
        <form method="post" id="form1">
            @if (Model != null)
            {
                <div class="search-form">
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-xxl-6 col">
                                @Html.Action("_OrganizeFilter", "Include", new { OID = Model.OID, OTitle = Model.OTitle, LockFlag = true })
                            </div>
                            <div class="col-xxl-6 col">
                                @Html.Action("_PhoneNoFilter", "Include", new { PhoneNo = Model.CellPhone, PhoneTitle = "輸入手機號碼", ZID = Model.CellPhoneZipID })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xxl-4 col-lg-6 col-12">
                                @Html.TextBox("txb_Name", @Model.Name, new { @class = "form-control form-control-lg input-underline", @placeholder = "姓名關鍵字" })
                            </div>
                            <div class="col-xxl-auto col-lg-6 col-12">
                                <div class="form-control-lg">
                                    <label>性別：</label>
                                    @Html.RadioButton("rbl_Sex", 0, (Model.Sex == 0), new { @class = "form-check-input" })
                                    @Html.Label("全部")
                                    @Html.RadioButton("rbl_Sex", 1, (Model.Sex == 1), new { @class = "form-check-input" })
                                    @Html.Label("男")
                                    @Html.RadioButton("rbl_Sex", 2, (Model.Sex == 2), new { @class = "form-check-input" })
                                    @Html.Label("女")
                                </div>
                            </div>

                            <div class="col-xxl-auto col-lg-6 col-12">
                                <div class="row">
                                    <div class="col-auto">
                                        <label class="form-control-lg ps-0 pe-0">受洗狀態：</label>
                                    </div>
                                    <div class="col-auto">
                                        @Html.DropDownList(Model.LS_Baptized.ControlName, Model.LS_Baptized.ddlList, new { @class = "form-select form-select-lg" })
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-xxl-6 col">
                                @Html.CheckBox("cbox_PoorFlag", Model.bPoorFlag, new { @class = "form-check-input" })
                                @Html.Label("中低收入戶")
                            </div>
                            <div class="col-xxl-6 col">
                                
                            </div>
                        </div>
                    </div>
                    <!--
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>課程分類</label>
                                    <select class="form-select form-select-lg">
                                        <option selected disabled>請選擇</option>
                                        <option value="1">One</option>
                                        <option value="2">Two</option>
                                        <option value="3">Three</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>課程名稱</label>
                                    <input class="form-control form-control-lg input-underline" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>事工團分類</label>
                                    <select class="form-select form-select-lg">
                                        <option selected disabled>請選擇</option>
                                        <option value="1">One</option>
                                        <option value="2">Two</option>
                                        <option value="3">Three</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>事工團名稱</label>
                                    <input class="form-control form-control-lg input-underline" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>其他備註</label>
                                    <input class="form-control form-control-lg input-underline" />
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>中低收入戶</label><br />
                                    <div class="check-container">
                                        <input class="form-check-input"
                                               type="checkbox"
                                               value="" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        -->
                    <div class="search-form-section">
                        <div class="d-flex justify-content-end">
                            <a href="javascript:;" onclick="document.getElementById('form1').submit();" class="btn btn-primary btn-lg btn-submit btn-round btn-submit me-2"><i class="fa-solid fa-magnifying-glass"></i>搜尋</a>
                        </div>
                    </div>
                </div>
                <div class="table-container">
                    <!--
    <div class="table-func-container">
        <button class="btn btn-outline-primary btn-sm btn-round">
            全選
        </button>
        <button class="btn btn-outline-primary btn-sm btn-round">
            全不選
        </button>
        <div>&nbsp;</div>
        <button id="btn-export-sm"
                class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出
        </button>
        <button class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出牧養歷程
        </button>
        <button class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出課程歷程
        </button>
        <button class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出事工歷程
        </button>
    </div>
        -->
                    <div class="table-container">
                        @Html.Action("_TableList", "Include", new { cTL = Model.cTL })
                    </div>
                </div>
            }

        </form>
    </div>
</div>

Banner/Areas/Admin/Views/AccountSet/Account_Baptized_List.cshtml
@model Banner.Areas.Admin.Controllers.AccountSetController.cAccount_List
@{
    Layout = "~/Areas/Admin/Views/Include/_Master.cshtml";
}

<div class="main-container">
    <div class="header-container">
        <div class="header-left-border"></div>
        <h5 class="header font-bold">@ViewBag._Title</h5>
    </div>
    <div class="body-container">
        <form method="post" id="form1">
            @if (Model != null)
            {
                <div class="search-form">
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-xxl-6 col">
                                @Html.Action("_OrganizeFilter", "Include", new { OID = Model.OID, OTitle = Model.OTitle, LockFlag = true })
                            </div>
                            <div class="col-xxl-6 col">
                                @Html.Action("_PhoneNoFilter", "Include", new { PhoneNo = Model.CellPhone, PhoneTitle = "輸入手機號碼", ZID = Model.CellPhoneZipID })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xxl-4 col-lg-6 col-12">
                                <div class="row">
                                    <div class="col-auto ms-0 me-0">
                                        <label class="form-control-lg ps-0 pe-0">姓名：</label>
                                    </div>
                                    <div class="col-auto ms-0 me-0">
                                        @Html.TextBox("txb_Name", @Model.Name, new { @class = "form-control form-control-lg input-underline", @placeholder = "姓名關鍵字" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-xxl-auto col-lg-6 col-12">
                                <div class="form-control-lg">
                                    <label>性別：</label>
                                    @Html.RadioButton("rbl_Sex", 0, (Model.Sex == 0), new { @class = "form-check-input" })
                                    @Html.Label("全部")
                                    @Html.RadioButton("rbl_Sex", 1, (Model.Sex == 1), new { @class = "form-check-input" })
                                    @Html.Label("男")
                                    @Html.RadioButton("rbl_Sex", 2, (Model.Sex == 2), new { @class = "form-check-input" })
                                    @Html.Label("女")
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-control-lg">
                                    <div class="row">
                                        @foreach (var cList in Model.LS_Baptized.ddlList)
                                        {
                                            <div class="col-xxl-auto col-lg-6 col-12 pt-2">
                                                @Html.RadioButton(Model.LS_Baptized.ControlName, cList.Value, cList.Selected, new { @class = "form-check-input", @id = Model.LS_Baptized.ControlName + cList.Value })
                                                @Html.Label(cList.Text, new { @for = Model.LS_Baptized.ControlName + cList.Value })
                                            </div>
                                            if (cList.Value == "1")
                                            {
                                                <div class="col-xxl-auto col-lg-6 col-12">
                                                    @Html.TextBox("txb_TargetDate", @Model.TargetDate, new { @class = "form-control form-control-lg input-underline", @placeholder = "指定日期", @type = "date" })
                                                </div>
                                            }

                                        }
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="search-form-section">
                        <div class="d-flex justify-content-end">
                            <a href="javascript:;" onclick="document.getElementById('form1').submit();" class="btn btn-primary btn-submit btn-lg btn-round btn-submit me-2"><i class="fa-solid fa-magnifying-glass"></i>搜尋</a>
                        </div>
                    </div>
                </div>
                <div class="table-container">
                    <div class="table-container">
                        @Html.Action("_TableList", "Include", new { cTL = Model.cTL })
                    </div>
                </div>
            }

        </form>
    </div>
</div>

Banner/Areas/Admin/Views/AccountSet/Account_Childen_List.cshtml
@model Banner.Areas.Admin.Controllers.AccountSetController.cAccount_List
@{
    Layout = "~/Areas/Admin/Views/Include/_Master.cshtml";
}

<div class="main-container">
    <div class="header-container">
        <div class="header-left-border"></div>
        <h5 class="header font-bold">@ViewBag._Title</h5>
    </div>
    <div class="body-container">
        <form method="post" id="form1">
            @if (Model != null)
            {
                <div class="search-form">
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-xxl-6 col">
                                @Html.TextBox("txb_Name", @Model.Name, new { @class = "form-control form-control-lg input-underline", @placeholder = "姓名關鍵字" })
                            </div>
                            <div class="col-xxl-6 col">
                                @Html.Action("_PhoneNoFilter", "Include", new { PhoneNo = Model.CellPhone, PhoneTitle = "輸入手機號碼", ZID = Model.CellPhoneZipID })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xxl-4 col-lg-6 col-12">
                                <div class="form-control-lg">
                                    <label>性別：</label>
                                    @Html.RadioButton("rbl_Sex", 0, (Model.Sex == 0), new { @class = "form-check-input" })
                                    @Html.Label("全部")
                                    @Html.RadioButton("rbl_Sex", 1, (Model.Sex == 1), new { @class = "form-check-input" })
                                    @Html.Label("男")
                                    @Html.RadioButton("rbl_Sex", 2, (Model.Sex == 2), new { @class = "form-check-input" })
                                    @Html.Label("女")
                                </div>
                            </div>
                            <div class="col-xxl-auto col-lg-6 col-12">
                                <div class="row">
                                    <div class="col-auto">
                                        <label class="form-control-lg ps-0 pe-0">受洗狀態：</label>
                                    </div>
                                    <div class="col-auto">
                                        @Html.DropDownList(Model.LS_Baptized.ControlName, Model.LS_Baptized.ddlList, new { @class = "form-select form-select-lg" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-xxl-auto col-lg-6 col-12">
                                @Html.CheckBox("cbox_PoorFlag", Model.bPoorFlag, new { @class = "form-check-input" })
                                @Html.Label("中低收入戶")
                            </div>

                        </div>
                    </div>
                    <!--
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>課程分類</label>
                                    <select class="form-select form-select-lg">
                                        <option selected disabled>請選擇</option>
                                        <option value="1">One</option>
                                        <option value="2">Two</option>
                                        <option value="3">Three</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>課程名稱</label>
                                    <input class="form-control form-control-lg input-underline" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>事工團分類</label>
                                    <select class="form-select form-select-lg">
                                        <option selected disabled>請選擇</option>
                                        <option value="1">One</option>
                                        <option value="2">Two</option>
                                        <option value="3">Three</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>事工團名稱</label>
                                    <input class="form-control form-control-lg input-underline" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="search-form-section">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>其他備註</label>
                                    <input class="form-control form-control-lg input-underline" />
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>中低收入戶</label><br />
                                    <div class="check-container">
                                        <input class="form-check-input"
                                               type="checkbox"
                                               value="" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        -->
                    <div class="search-form-section">
                        <div class="d-flex justify-content-end">
                            <a href="javascript:;" onclick="document.getElementById('form1').submit();" class="btn btn-primary btn-submit btn-lg btn-round btn-submit me-2"><i class="fa-solid fa-magnifying-glass"></i>搜尋</a>
                        </div>
                    </div>
                </div>
                <div class="table-container">
                    <!--
    <div class="table-func-container">
        <button class="btn btn-outline-primary btn-sm btn-round">
            全選
        </button>
        <button class="btn btn-outline-primary btn-sm btn-round">
            全不選
        </button>
        <div>&nbsp;</div>
        <button id="btn-export-sm"
                class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出
        </button>
        <button class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出牧養歷程
        </button>
        <button class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出課程歷程
        </button>
        <button class="btn btn-primary btn-sm btn-round">
            <i class="fa-solid fa-download"></i>匯出事工歷程
        </button>
    </div>
        -->
                    <div class="table-container">
                        @Html.Action("_TableList", "Include", new { cTL = Model.cTL })
                    </div>
                </div>
            }

        </form>
    </div>
</div>